name: Firebase Functions on Merge
on:
  push:
    branches:
      - main
jobs:
  main:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
      - run: cd functions
      - run: npm ci
      - name: Deploy functions to Firebase
        run: firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}
